export const NETWORK_EVENTS = Object.freeze({
    "CONNECT": "connect",
    "DISCONNECT": "disconnect",
    "MESSAGE": "MESSAGE",
    "REGISTER": "REGISTER",
    "CREATE_ROOM_REQUEST": "CREATE_ROOM_REQUEST",
    "JOIN_ROOM_REQUEST": "JOIN_ROOM_REQUEST",
    "LEAVE_ROOM_REQUEST": "LEAVE_ROOM_REQUEST",
    "MESSAGE_ROOM_REQUEST": "MESSAGE_ROOM_REQUEST"
});

export const ROOM_EVENTS = Object.freeze({
    "ROOM_UPDATE": "ROOM_UPDATE",
    "KICK_CLIENT": "KICK_CLIENT",
    "READY_CLIENT": "READY_CLIENT",
    "UNREADY_CLIENT": "UNREADY_CLIENT",
    "START_INSTANCE": "START_INSTANCE"
});
